### ISSUE TITLE
Support for Norwegian "National Identification Number Name"?

### ISSUE THREAD

**Issue by joelmandell** [anghelvalentin/CountryValidator#2]
Hi,
I wonder if "National Identification Number Name" for Norway is implemented?
There is code for it in the repository?

**Comment by anghelvalentin** [comment]
Hello,
Yes: 
https://github.com/anghelvalentin/CountryValidator/blob/master/CountryValidator/CountriesValidators/NorwayValidator.cs

Is the same validation that is used to validate the Individual Tax Code (Fødselsnummer).
